import {
  Ribbon,
  Bone,
  Brain,
  Wind,
  Activity,
  Droplets,
  HeartPulse,
  Shield,
  Utensils,
  Scan,
  CircleDot,
  FlaskConical,
  Baby,
  Heart,
  Stethoscope,
  Moon,
  CloudRain,
} from "lucide-react";


export const clinicalServices = [
  {
    id: 2,
    icon: Droplets,
    title: "Metabolic & Endocrine Disorders",
    diseases: [
      "Diabetes",
      "Hypertension (High BP)",
      "High Cholesterol",
      "Uric Acid (Gout/Hyperuricemia)",
      "Thyroid Disorders",
      "Metabolic Syndrome",
    ],
  },
  {
    id: 3,
    icon: Utensils,
    title: "Digestive & Gastrointestinal Disorders",
    diseases: [
      "Gastritis",
      "IBS",
      "Acid Reflux (GERD)",
      "Peptic Ulcer",
      "Constipation",
      "Diarrhea",
      "Fatty Liver",
      "Liver Disorders",
      "Gallstones",
      "Piles (Hemorrhoids)",
      "Fistula",
      "Fissure",
      "Hernia",
    ],
  },
  {
    id: 4,
    icon: CircleDot,
    title: "Kidney & Urology",
    diseases: [
      "Kidney Diseases",
      "Kidney Stones",
      "Urinary Tract Infection (UTI)",
      "Frequent Urination",
      "Urinary Incontinence",
      "Enlarged Prostate (BPH)",
      "General Urological Disorders",
    ],
  },
  {
    id: 5,
    icon: HeartPulse,
    title: "Cardiovascular & Vascular Disorders",
    diseases: [
      "Cardiovascular Diseases",
      "Heart Disease",
      "Varicose Veins",
      "Poor Circulation",
      "Peripheral Vascular Disease",
    ],
  },
  {
    id: 6,
    icon: Wind,
    title: "Respiratory Disorders",
    diseases: [
      "Asthma",
      "Respiratory Diseases",
      "Bronchitis",
      "COPD",
      "Pneumonia",
      "Allergic Rhinitis",
      "Sinusitis",
    ],
  },
  {
    id: 7,
    icon: Brain,
    title: "Neurological Disorders",
    diseases: [
      "Nerve-related Disorders",
      "Sciatica",
      "Paralysis",
      "Neuropathy",
      "Migraine",
      "Chronic Headaches",
      "Tremors",
      "Vertigo",
      "Neuralgia",
    ],
  },
  {
    id: 8,
    icon: Bone,
    title: "Musculoskeletal & Orthopedic Disorders",
    diseases: [
      "Arthritis",
      "Osteoarthritis",
      "Rheumatoid Arthritis",
      "Spondylitis",
      "Cervical Spondylosis",
      "Lumbar Spondylosis",
      "Back Pain",
      "Neck Pain",
      "Frozen Shoulder",
      "Joint Pain",
      "Muscle Pain",
      "Fibromyalgia",
    ],
  },
  {
    id: 9,
    icon: Scan,
    title: "Skin Disorders",
    diseases: [
      "Psoriasis",
      "Eczema",
      "Dermatitis",
      "Acne",
      "Fungal Infections",
      "Vitiligo",
      "Skin Allergies",
      "General Skin Diseases",
    ],
  },
  {
    id: 10,
    icon: Baby,
    title: "Women's Health (Gynecology)",
    diseases: [
      "Gynaecological Disorders",
      "PCOS/PCOD",
      "Menstrual Disorders",
      "Fibroids",
      "Ovarian Cysts",
      "Leucorrhoea",
      "Menopause-related Problems",
    ],
  },
  {
    id: 11,
    icon: Stethoscope,
    title: "Men's Health",
    diseases: [
      "Enlarged Prostate (BPH)",
      "Erectile Dysfunction",
      "Premature Ejaculation",
    ],
  },
  {
    id: 1,
    icon: Ribbon,
    title: "Cancer & Tumors",
    diseases: [
      "Cancer",
      "Tumors",
      "Benign Tumors",
      "Cysts",
    ],
  },
  {
    id: 14,
    icon: Shield,
    title: "Blood & Immune Disorders",
    diseases: [
      "Anemia",
      "Low Immunity",
      "Frequent Infections",
      "Autoimmune Disorders",
    ],
  },
  {
    id: 12,
    icon: FlaskConical,
    title: "Infertility & Reproductive Health",
    diseases: [
      "Male Infertility",
      "Female Infertility",
      "Hormonal Imbalances",
      "Reproductive Health Disorders",
    ],
  },
  {
    id: 13,
    icon: Activity,
    title: "ENT Disorders",
    diseases: [
      "Ear Disorders",
      "Nose Disorders",
      "Throat Disorders",
      "Sinusitis",
      "Tinnitus",
      "Hearing Problems",
      "Tonsillitis",
    ],
  },
  {
    id: 15,
    icon: Moon,
    title: "Mental Health & Sleep Disorders",
    diseases: [
      "Anxiety",
      "Stress",
      "Depression",
      "Insomnia",
      "Sleep Disorders",
      "Fatigue",
      "Burnout",
    ],
  },
  {
    id: 16,
    icon: CloudRain,
    title: "Allergic Disorders",
    diseases: [
      "Food Allergies",
      "Seasonal Allergies",
      "Dust Allergies",
      "Drug Allergies",
    ],
  },
  {
    id: 17,
    icon: Heart,
    title: "Geriatric (Age-related) Disorders",
    diseases: [
      "Osteoporosis",
      "Age-related Weakness",
      "Balance Problems",
      "Memory Concerns",
    ],
  },
];